web-dahuyou/NiceTab

entrypoints/common/locale/modules/home/enUS.ts, entrypoints/common/locale/modules/home/zhCN.ts, entrypoints/common/storage.ts, entrypoints/options/home/MoveToModal.tsx, entrypoints/options/home/TabGroup.tsx, entrypoints/options/home/hooks/moveTo.ts, entrypoints/options/home/index.tsx, entrypoints/options/home/types.ts, package.json
- 全选标签页穿越后清空标签组
- 标签组和标签页移动穿越时支持合并重复项
=> 标签组和标签页穿越功能优化

entrypoints/common/storage/tabListUtils.ts
=> 新增按字母升序降序排序功能

entrypoints/common/components/DndComponent.tsx, entrypoints/common/hooks/global.ts, entrypoints/options/home/TabListItem.styled.tsx, entrypoints/options/home/TabListItem.tsx, entrypoints/types/global.ts, package.json, pnpm-lock.yaml
=> 标签页标题hover时展示标题和链接

entrypoints/common/locale/modules/sync/enUS.ts, entrypoints/common/locale/modules/sync/zhCN.ts, entrypoints/common/storage/syncUtils.ts, entrypoints/options/home/SortingBtns.tsx, entrypoints/options/sync/Sync.styled.tsx, entrypoints/options/sync/SyncResultList.tsx, entrypoints/options/sync/index.tsx, package.json
=> 修复 github API 同步问题

entrypoints/background/index.ts, entrypoints/common/contextMenus.ts, entrypoints/common/tabs.ts, package.json
=> contextMenus update

entrypoints/common/contextMenus.ts
=> 手残了, 改出毛病了

entrypoints/common/components/DndComponent.tsx, entrypoints/common/locale/modules/sync/enUS.ts, entrypoints/common/locale/modules/sync/zhCN.ts, entrypoints/options/home/TabListItem.tsx, entrypoints/options/sync/components/gist/SidebarContentModule.tsx, entrypoints/options/sync/components/webdav/SidebarContentModule.tsx, entrypoints/options/sync/index.tsx, entrypoints/types/global.ts, package.json
=> 新增一键推送本地数据到所有远程存储

entrypoints/popup/App.tsx
=> 调整stopPropagation位置

entrypoints/common/components/Root.tsx, entrypoints/common/style/Common.styled.tsx, entrypoints/content/App.tsx, entrypoints/options/home/Home.styled.tsx, entrypoints/options/home/MoveToModal.tsx, entrypoints/options/home/RenderTreeNode.tsx, entrypoints/options/home/SendTargetModal.tsx, entrypoints/options/settings/index.tsx, package.json
=> 隔离样式, 防止样式和主题污染

entrypoints/common/components/DelayedComponent.tsx, entrypoints/common/constants.ts, entrypoints/common/locale/modules/settings/enUS.ts, entrypoints/common/locale/modules/settings/zhCN.ts, entrypoints/common/storage/settingsUtils.ts, entrypoints/options/home/Home.styled.tsx, entrypoints/options/home/RenderTreeNode.tsx, entrypoints/options/home/TabGroup.tsx, entrypoints/options/home/TabItemEditModal.tsx, entrypoints/options/home/hooks/homeCustomEvent.ts, entrypoints/options/home/hooks/treeData.ts, entrypoints/options/home/index.tsx, entrypoints/options/settings/index.tsx, entrypoints/types/global.ts, package.json
=> 列表页展示全部按钮恢复展示, 其他交互优化

entrypoints/common/constants.ts, entrypoints/common/hooks/global.ts, entrypoints/common/locale/modules/home/enUS.ts, entrypoints/common/locale/modules/home/zhCN.ts, entrypoints/common/locale/modules/settings/enUS.ts, entrypoints/common/locale/modules/settings/zhCN.ts, entrypoints/common/storage/settingsUtils.ts, entrypoints/common/style/Common.styled.tsx, entrypoints/options/home/TabGroup.tsx, entrypoints/options/home/TabGroupList.tsx, entrypoints/options/home/TabListItem.tsx, entrypoints/options/settings/index.tsx, entrypoints/types/global.ts
- 问题修复
- 新增删除标签页是否需要确认的配置项及确认弹窗
=> 问题修复和新增配置项

entrypoints/options/home/TabListItem.tsx, entrypoints/options/home/hooks/treeData.ts, package.json
=> 打开标签页自动删除标签页时保留锁定的标签页

entrypoints/common/locale/modules/sync/enUS.ts, entrypoints/common/locale/modules/sync/zhCN.ts, entrypoints/common/storage/syncUtils.ts, entrypoints/common/storage/syncWebDAVUtils.ts, entrypoints/options/recycleBin/index.tsx, entrypoints/options/settings/index.tsx, entrypoints/options/sync/footer/Footer.styled.tsx, entrypoints/options/sync/footer/index.tsx, entrypoints/options/sync/index.tsx
=> 新增支持偏好设置信息的远程同步

entrypoints/options/settings/index.tsx
=> divider标题位置调整

README.md, entrypoints/common/utils/importExport.ts, entrypoints/options/importExport/constants.ts, entrypoints/options/importExport/index.tsx, entrypoints/options/importExport/types.ts, entrypoints/types/tabList.ts
=> merge pr_120

README.md, entrypoints/common/utils/importExport.ts, entrypoints/options/importExport/constants.ts, entrypoints/options/importExport/index.tsx, entrypoints/types/tabList.ts
http://keptab.com/
刚才看了下 NiceTab，发现有同步功能，喜欢，所以提了个 PR 把我的 keptab 数据转过来
=> feat: Add keptab import and export

entrypoints/common/hooks/global.ts, entrypoints/common/locale/index.ts, entrypoints/common/locale/modules/common/enUS.ts, entrypoints/common/locale/modules/common/zhCN.ts, entrypoints/common/locale/modules/home/enUS.ts, entrypoints/common/locale/modules/home/zhCN.ts, entrypoints/common/locale/modules/hotkeys/enUS.ts, entrypoints/common/locale/modules/hotkeys/zhCN.ts, entrypoints/common/locale/modules/importExport/enUS.ts, entrypoints/common/locale/modules/importExport/zhCN.ts, entrypoints/common/locale/modules/settings/enUS.ts, entrypoints/common/locale/modules/settings/zhCN.ts, entrypoints/common/locale/modules/sync/enUS.ts, entrypoints/common/locale/modules/sync/zhCN.ts, entrypoints/options/App.tsx, entrypoints/options/home/MoveToModal.tsx, entrypoints/options/home/hooks/hotkeys.ts, entrypoints/types/global.ts
- 收束国际化key值的类型。
- 确保每组国际化之间的key都是同步的，防止遗漏或者对应不上
=> refactor: 增强国际化类型安全

CONTRIBUTING-zh.md, CONTRIBUTING.md, README-zh.md, README.md, entrypoints/options/importExport/index.tsx, entrypoints/options/settings/index.tsx
- 中英文档
- 增加代码提交说明
- 增加持久化存储用户数据的说明
=> docs: 增加CONTRIBUTING文档

README-zh.md, README.md, entrypoints/background/index.ts, entrypoints/common/constants.ts, entrypoints/common/contextMenus.ts, entrypoints/common/envVars.ts, entrypoints/common/locale/modules/common/enUS.ts, entrypoints/common/locale/modules/common/zhCN.ts, entrypoints/common/locale/modules/home/enUS.ts, entrypoints/common/locale/modules/home/zhCN.ts, entrypoints/common/storage/settingsUtils.ts, entrypoints/content/index.tsx, entrypoints/options/App.tsx, entrypoints/options/home/Home.styled.tsx, entrypoints/options/home/index.tsx, entrypoints/options/index.html, entrypoints/options/settings/index.tsx, entrypoints/popup/App.tsx, package.json, pnpm-lock.yaml, wxt.config.ts
=> feat-firefox

README-zh.md, README.md, entrypoints/common/utils/common.ts, entrypoints/common/utils/importExport.ts, entrypoints/options/components/EditInput.tsx, entrypoints/options/home/MoveToModal.tsx, entrypoints/options/home/RenderTreeNode.tsx, entrypoints/options/home/SendTargetModal.tsx, entrypoints/options/home/TabGroup.tsx, entrypoints/options/home/TabGroupRecycle.tsx, entrypoints/options/home/utils.tsx, entrypoints/options/importExport/constants.ts, entrypoints/options/importExport/index.tsx, entrypoints/types/tabList.ts
- SessionBuddy扩展数据适配
- 分类和标签组名称字数限制调整，目录选择弹窗样式优化
=> SessionBuddy扩展数据适配
